// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcT2eibp6ERxHD6JIPQR_i3XcJL4WC7rs',
    appId: '1:233378636806:web:76d88155fb993afb36cf87',
    messagingSenderId: '233378636806',
    projectId: 'pulse-flutter-5e725',
    authDomain: 'pulse-flutter-5e725.firebaseapp.com',
    storageBucket: 'pulse-flutter-5e725.firebasestorage.app',
    measurementId: 'G-PKC2ZG2386',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6LTHl6I9HR0LiUmTcOzRmeh552Bdlqvo',
    appId: '1:233378636806:android:dbcd122c9bce5ac236cf87',
    messagingSenderId: '233378636806',
    projectId: 'pulse-flutter-5e725',
    storageBucket: 'pulse-flutter-5e725.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7FA0_rfbIG_vWUYdcotkKmnlEvCCQBbM',
    appId: '1:233378636806:ios:50fc0cc65fa0097e36cf87',
    messagingSenderId: '233378636806',
    projectId: 'pulse-flutter-5e725',
    storageBucket: 'pulse-flutter-5e725.firebasestorage.app',
    iosBundleId: 'com.example.pulseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7FA0_rfbIG_vWUYdcotkKmnlEvCCQBbM',
    appId: '1:233378636806:ios:50fc0cc65fa0097e36cf87',
    messagingSenderId: '233378636806',
    projectId: 'pulse-flutter-5e725',
    storageBucket: 'pulse-flutter-5e725.firebasestorage.app',
    iosBundleId: 'com.example.pulseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcT2eibp6ERxHD6JIPQR_i3XcJL4WC7rs',
    appId: '1:233378636806:web:9d71c85b1e3daecf36cf87',
    messagingSenderId: '233378636806',
    projectId: 'pulse-flutter-5e725',
    authDomain: 'pulse-flutter-5e725.firebaseapp.com',
    storageBucket: 'pulse-flutter-5e725.firebasestorage.app',
    measurementId: 'G-2TME8EDRXZ',
  );
}
